
services:
  brainstem:
    build:
      context: ..
      dockerfile: docker/brainstem.Dockerfile
    container_name: brainstem_4070
    ports:
      - "5001:5001"
    environment:
      - BRAINSTEM_DEVICE=cpu
    networks:
      - nexusnet

  nas:
    build:
      context: ..
      dockerfile: docker/nas.Dockerfile
    container_name: nas_memory
    ports:
      - "5002:5002"
    volumes:
      - ../data/nas:/data/nas
    networks:
      - nexusnet

      
networks:
  nexusnet:
    driver: bridge
